### PR TITLE
Capitalize macro names to avoid conflicts with the Boost library.

### PR DESCRIPTION
**Pull request by rtohid**

### CODE REVIEW

**Comment by charest** [comment]
What is the issue?

**Comment by rtohid** [comment]
The HPX backend of FleCSI links against the boost library and the naming conflicts cause compilation errors.

**Comment by charest** [comment]
Flecsi itself links against the boost libraries and we dont see this issue.  Can you show the error you are getting?

**Comment by rtohid** [comment]
I think FleCSI only depends on boost's preprocessor. Here is the error I get:
 
```
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/lagrange_eqns.h:17,
                 from /home/rod/src/flecsale/apps/maire_hydro/2d/../types.h:14,
                 from /home/rod/src/flecsale/apps/maire_hydro/2d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/maire_hydro/2d/driver.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/lagrange_eqns.h:17,
                 from /home/rod/src/flecsale/apps/maire_hydro/2d/../types.h:14,
                 from /home/rod/src/flecsale/apps/maire_hydro/2d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/maire_hydro/2d/inputs.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/euler_eqns.h:16,
                 from /home/rod/src/flecsale/apps/hydro/3d/../types.h:14,
                 from /home/rod/src/flecsale/apps/hydro/3d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/hydro/3d/inputs.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/euler_eqns.h:16,
                 from /home/rod/src/flecsale/apps/hydro/1d/../types.h:14,
                 from /home/rod/src/flecsale/apps/hydro/1d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/hydro/1d/inputs.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/lagrange_eqns.h:17,
                 from /home/rod/src/flecsale/apps/maire_hydro/1d/../types.h:14,
                 from /home/rod/src/flecsale/apps/maire_hydro/1d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/maire_hydro/1d/driver.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/lagrange_eqns.h:17,
                 from /home/rod/src/flecsale/apps/maire_hydro/3d/../types.h:14,
                 from /home/rod/src/flecsale/apps/maire_hydro/3d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/maire_hydro/3d/inputs.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/euler_eqns.h:16,
                 from /home/rod/src/flecsale/apps/hydro/2d/../types.h:14,
                 from /home/rod/src/flecsale/apps/hydro/2d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/hydro/2d/driver.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/lagrange_eqns.h:17,
                 from /home/rod/src/flecsale/apps/maire_hydro/3d/../types.h:14,
                 from /home/rod/src/flecsale/apps/maire_hydro/3d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/maire_hydro/3d/driver.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/euler_eqns.h:16,
                 from /home/rod/src/flecsale/apps/hydro/2d/../types.h:14,
                 from /home/rod/src/flecsale/apps/hydro/2d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/hydro/2d/inputs.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/euler_eqns.h:16,
                 from /home/rod/src/flecsale/apps/hydro/1d/../types.h:14,
                 from /home/rod/src/flecsale/apps/hydro/1d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/hydro/1d/driver.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/lagrange_eqns.h:17,
                 from /home/rod/src/flecsale/apps/maire_hydro/1d/../types.h:14,
                 from /home/rod/src/flecsale/apps/maire_hydro/1d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/maire_hydro/1d/inputs.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
In file included from /home/rod/src/flecsale/ristra/ristra/math/general.h:15:0,
                 from /home/rod/src/flecsale/flecsale/eqns/euler_eqns.h:16,
                 from /home/rod/src/flecsale/apps/hydro/3d/../types.h:14,
                 from /home/rod/src/flecsale/apps/hydro/3d/inputs.h:13,
                 from /home/rod/src/flecsale/apps/hydro/3d/driver.cc:11:
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:36:3: error: expected unqualified-id before ‘do’
   do {                                                                         \
   ^
/home/rod/src/flecsale/ristra/ristra/assertions/errors.h:40:5: error: expected unqualified-id before ‘while’
   } while(0)
     ^
```

**Comment by charest** [comment]
@ktsai7 Do you know why the ci status is still  "Waiting for status to be reported"

**Comment by ktsai7** [comment]
@charest Can someone resolve the conflicts? That could be what’s blocking and if not, I’ll take a look.

**Comment by ollielo** [comment]
It looks like this PR missed some places in the search/replace.  This does not show up until you compile flecsale with lua enabled.

`[ollie@localhost ristra]$ grep -r throw_runtime_error *
ristra/embedded/embed_lua.h:     throw_runtime_error( "Invalid conversion of type \"" <<
ristra/embedded/embed_lua.h:     throw_runtime_error( "Invalid conversion of type \"" <<
ristra/embedded/embed_lua.h:     throw_runtime_error( "Invalid conversion of type \"" <<
ristra/embedded/embed_lua.h:     throw_runtime_error( "Invalid conversion of type \"" <<
ristra/embedded/embed_lua.h:     throw_runtime_error( "Invalid conversion of type \"" <<
ristra/embedded/embed_lua.h:     throw_runtime_error( "Invalid conversion of type \"" <<
ristra/embedded/embed_lua.h:      throw_runtime_error( 
ristra/embedded/embed_lua.h:     throw_runtime_error( "Invalid conversion of type \"" <<
ristra/embedded/embed_lua.h:      throw_runtime_error( 
ristra/embedded/embed_lua.h:    throw_runtime_error(ss.str());
ristra/embedded/embed_lua.h:      throw_runtime_error(ss.str());
ristra/embedded/embed_lua.h:      throw_runtime_error("\"" << name << "\" does not exist.");
ristra/embedded/embed_lua.h:      throw_runtime_error("\"" << name << "\" is not a table.");
ristra/embedded/embed_lua.h:      throw_runtime_error("\"" << name << "\" returned nil.");
ristra/embedded/embed_lua.h:      throw_runtime_error("\"" << name << "\" is not a function.");
ristra/embedded/embed_lua.h:      throw_runtime_error( "Expecting 1 result, stack has " << refs_.size() );
ristra/embedded/embed_lua.h:      throw_runtime_error( 
ristra/embedded/embed_lua.h:      throw_runtime_error("Problem calling \"" << name_ << "\".");
`

**Pull request merged**
