### PR TITLE
Updated verions with more functionality

### PR DESCRIPTION
**Pull request by Jacob-Moore**
Added a few new element types.

### CODE REVIEW

**Comment by ddaniel** [comment]
@Jacob-Moore -- the elements tests are failing on the Fedora builds, but passing on the Ubuntu builds.  We need to resolve this before merging.

**Comment by charest** [comment]
4/24 Test  #4: ristra_elements ..................***Exception: SegFault  0.22 sec

**Comment by charest** [comment]
Looks like the elements test is failing

**Comment by Jacob-Moore** [comment]
Ok.  Once my desktop is back up and running (boot drive broke) I will rebuild it here to see if I can track down the problem.


Thanks for letting me know.


-Jacob

________________________________

**Comment by junghans** [comment]
Unfortunately libristra doesn't use gitlab CI yet, otherwise this would be the perfect case to use the new [`debug_build.sh` script](https://github.com/laristra/flecsi/blob/features/ktsai/travis_stages/developer/debug_build.sh) @ktsai7 wrote.

**Review by ddaniel — APPROVED** [review]
👍

@ktsai7 @junghans Perhaps we should should consider a bounds-checking build option for gitlab CI.  It would have helped here.

**Comment by junghans** [comment]
Sure we can roll that into the debug build, You you disabled all tests? Why?

**Comment by ddaniel** [comment]
I did?  Novice error if so.

**Pull request merged**
